# Generated by Django 6.0.2 on 2026-02-19 01:48

import django.db.models.deletion
import django.utils.timezone
import isbn_field.fields
import isbn_field.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('writer', models.CharField(max_length=255, verbose_name='著者')),
                ('publication_date', models.DateField(verbose_name='出版日')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='表紙画像')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品一覧',
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='版数')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='libraryApp.book', verbose_name='作品')),
            ],
            options={
                'verbose_name': '蔵書個体',
                'verbose_name_plural': '蔵書個体一覧',
            },
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lending', '貸出中'), ('returned', '返却済み')], default='lending', max_length=10, verbose_name='状態')),
                ('lending_date', models.DateField(default=django.utils.timezone.now, verbose_name='貸出日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='返却予定日')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='返却日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraryApp.bookitem', verbose_name='貸出個体')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': '貸出情報',
                'verbose_name_plural': '貸出情報一覧',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約日時')),
                ('status', models.CharField(choices=[('active', '予約中'), ('completed', '貸出完了'), ('cancelled', 'キャンセル')], default='active', max_length=20, verbose_name='予約状態')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.book', verbose_name='予約作品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='予約者')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約一覧',
            },
        ),
    ]
