# Generated by Django 6.0.2 on 2026-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='出版日'),
        ),
    ]
