# Generated by Django 6.0.2 on 2026-03-05 05:21

import isbn_field.fields
import isbn_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(max_length=28, unique=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
