# Generated by Django 6.0.2 on 2026-03-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0004_remove_book_image_book_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='出版日'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='購入日'),
        ),
    ]
