# Generated by Django 6.0.2 on 2026-03-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_alter_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='status',
            field=models.CharField(choices=[('lending', '貸出中'), ('lend_ok', '貸出可能')], default='lending', max_length=10, verbose_name='状態'),
        ),
    ]
