# Generated by Django 6.0.2 on 2026-03-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0006_alter_lending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='貸出可能フラグ'),
        ),
    ]
