# Generated by Django 6.0.2 on 2026-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0007_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='価格'),
        ),
    ]
